HEADER:
  label: "About me"

PRESENTATION:
  description: |
    I'm a Backend Developer and a Freelancer with a passion for building robust, scalable, and efficient systems. I specialize in designing and implementing server-side logic, databases, and APIs that power seamless digital experiences.

    My job is to ensure that everything runs smoothly behind the scenes, from data management to authentication and third-party integrations. I focus on writing clean, maintainable code and optimizing performance to handle high traffic and complex workflows.

DOING:
  enabled: true
  label: "What I'm doing"
  items:
    - title: "API Development"
      icon: "config/assets/icons/server-svgrepo-com.svg"
      description: "Building robust and scalable RESTful for seamless data exchange."
    - title: "Database Management"
      icon: "config/assets/icons/database.svg"
      description: "Designing, optimizing, and managing SQL and NoSQL databases for high performance."
    - title: "Authentication & Security"
      icon: "config/assets/icons/lock-alt-svgrepo-com.svg"
      description: "Implementing secure authentication, authorization, and encryption strategies."
    - title: "Swagger Documentation"
      icon: "config/assets/icons/swagger-svgrepo-com.svg"
      description: "Creating clear and interactive API documentation using Swagger."

SKILLS:
  enabled: true
  label: "Soft Skills"
  items:
    - title: "Fast Learner"
      icon: "config/assets/icons/bolt.svg"
      description: "I have the ability to quickly acquire new knowledge and adapt to changing technological environments."
    - title: "Teamwork"
      icon: "config/assets/icons/user.svg"
      description: "I collaborate effectively in multidisciplinary projects and communicate clearly with team members."
    - title: "Problem Solving"
      icon: "config/assets/icons/gear.svg"
      description: "I am creative and efficient in identifying and solving technical problems."
    - title: "Effective Communication"
      icon: "config/assets/icons/comment.svg"
      description: "I have the skill to convey ideas clearly and concisely, both technically and non-technically."

TECHNOLOGIES:
  enabled: true
  label: "Tech Experience"
  items:
    - title: "Python"
      icon: "config/assets/icons/python.svg"
    - title: "Flutter"
      icon: "config/assets/icons/flutter.svg"
    - title: "Git"
      icon: "config/assets/icons/git.svg"
    - title: "Figma"
      icon: "config/assets/icons/figma.svg"
    - title: "Firebase"
      icon: "config/assets/icons/firebase.svg"
    - title: "Pandas"
      icon: "config/assets/icons/pandas.svg"
    - title: "MongoDB"
      icon: "config/assets/icons/mongodb.svg"
    - title: "Dart"
      icon: "config/assets/icons/dart.svg"
    - title: "HTML"
      icon: "config/assets/icons/html.svg"
    - title: "AI"
      icon: "config/assets/icons/ai.svg"
    - title: "Jupyter"
      icon: "config/assets/icons/jupyter.svg"
    - title: "Linux"
      icon: "config/assets/icons/linux.svg"
