# We are using the ionicons icon set https://ionic.io/ionicons
# For example, to add a linkedin icon:
# <ion-icon name="logo-linkedin"></ion-icon>
# - icon: "logo-linkedin"

HEADER:
  label: "Show Contacts"

USER:
  role: "Backend Developer/Freelancer"
  name: "Ujjan Kumar Joshi"
  username: "ujjanjoshi" # <-- This needs to be the same as your GitHub username
  avatar: "config/assets/avatars/avatar-1.png"

INFO:
  - label: "Email"
    value: "ujjanjoshi3@gmail.com"
    icon: "mail-outline"
  - label: "Phone"
    value: "+(977) 9860900731"
    icon: "phone-portrait-outline"
  - label: "Birthday"
    value: "February 02, 2000"
    icon: "calendar-outline"
  - label: "Location"
    value: "Kathmandu, Nepal"
    icon: "location-outline"

SOCIAL:
  - icon: "logo-linkedin"
    url: "https://www.linkedin.com/in/ujjan-joshi-0817b2265/"
  - icon: "logo-github"
    url: "https://github.com/ujjanjoshi"
  - icon: "config/assets/icons/mobile.svg"
    url: "https://www.fiverr.com/s/BRG4bDW"
