HEADER:
  label: "Portfolio"

PROJECTS:
  - title: "GeoSpectrum Technologies Inc"
    category: "API/Laravel"
    image: "https://www.pngall.com/wp-content/uploads/13/Github-Logo-PNG-Image.png"
    url: "#"

  - title: "Social Influencer"
    category: "API/NodeJS"
    image: "https://www.pngall.com/wp-content/uploads/13/Github-Logo-PNG-Image.png"
    url: "https://github.com/ivansaul/flutter_coffee_shop_app#screenshots"

  - title: "PetShop"
    category: "API/Laravel"
    image: "https://www.pngall.com/wp-content/uploads/13/Github-Logo-PNG-Image.png"
    url: "#"

  - title: "Hyrgpt"
    category: "API/NodeJS"
    image: "https://www.pngall.com/wp-content/uploads/13/Github-Logo-PNG-Image.png"
    url: "#"

  - title: "Wave work"
    category: "API/NodeJS"
    image: "https://www.pngall.com/wp-content/uploads/13/Github-Logo-PNG-Image.png"
    url: "#"

  - title: "Hiry"
    category: "API/Python"
    image: "https://www.pngall.com/wp-content/uploads/13/Github-Logo-PNG-Image.png"
    url: "#"

  - title: "Seo-Nerd"
    category: "API/Laravel"
    image: "https://www.pngall.com/wp-content/uploads/13/Github-Logo-PNG-Image.png"
    url: "#"

  - title: "Wally"
    category: "API/NestJS"
    image: "https://www.pngall.com/wp-content/uploads/13/Github-Logo-PNG-Image.png"
    url: "#"

  - title: "School Management System"
    category: "API/Laravel"
    image: "https://www.pngall.com/wp-content/uploads/13/Github-Logo-PNG-Image.png"
    url: "#"

  - title: "Kafter LMS"
    category: "API/NestJS"
    image: "https://www.pngall.com/wp-content/uploads/13/Github-Logo-PNG-Image.png"
    url: "#"