HEADER:
  label: "Portfolio"

PROJECTS:
  - title: "GeoSpectrum Technologies Inc"
    category: "API/Laravel"
    image: "config/assets/icons/laravel-svgrepo-com.svg"
    url: "#"

  - title: "Social Influencer"
    category: "API/NodeJS"
    image: "config/assets/icons/nodejs-svgrepo-com.svg"
    url: "#"

  - title: "PetShop"
    category: "API/Laravel"
    image: "config/assets/icons/laravel-svgrepo-com.svg"
    url: "#"

  - title: "Hyrgpt"
    category: "API/NodeJS"
    image: "config/assets/icons/nodejs-svgrepo-com.svg"
    url: "#"

  - title: "Wave work"
    category: "API/NodeJS"
    image: "config/assets/icons/nodejs-svgrepo-com.svg"
    url: "#"

  - title: "Hiry"
    category: "API/Python"
    image: "config/assets/icons/python.svg"
    url: "#"

  - title: "Seo-Nerd"
    category: "API/Laravel"
    image: "config/assets/icons/laravel-svgrepo-com.svg"
    url: "#"

  - title: "Wally"
    category: "API/NestJS"
    image: "config/assets/icons/nestjs-svgrepo-com.svg"
    url: "#"

  - title: "School Management System"
    category: "API/Laravel"
    image: "config/assets/icons/laravel-svgrepo-com.svg"
    url: "#"

  - title: "Kafter LMS"
    category: "API/NestJS"
    image: "config/assets/icons/nestjs-svgrepo-com.svg"
    url: "#"