HEADER:
  label: "Resume"

EDUCATION:
  enabled: true
  label: "Education"
  items:
    - period: "June, 2016"
      institution: "SLC"
      description: "Universal College Preparatory School"
    - period: "June, 2018"
      institution: "+2"
      description: "National School of Sciences"
    - period: "December, 2023"
      institution: "Bachelors of Information Technology (BIM)"
      description: "National College of Computer Studies"
    
EXPERIENCE:
  enabled: true
  label: "Experience"
  items:
    - period: "February, 2023 - July, 2023"
      position: "Back-End Developer (INTERN)"
      description: "As a Laravel Developer at Krafter's Technology, I played a pivotal role in enhancing the functionality of the School Management System through the development and integration of advanced notification APIs using WebSockets."
    - period: "September, 2023 - Present"
      position: "FREELANCING"
      description: "As a freelancer, I've played a pivotal role in numerous projects where I utilized NestJS to develop robust APIs."
    - period: "August, 2023 - Present"
      position: "Junior Software Engineer (REMOTE)"
      description: "As a Software Engineer, I played a key role in a big project using Laravel, NodeJs. I worked with a team from the start to finish, making sure everything went smoothly, from coming up with the idea to getting the project up and running."

LANGUAGES:
  enabled: true
  display_progress_bars: true
  display_percentage_values: false
  label: "Languages"
  items:
    - language: "English"
      proficiency: "100%"
    - language: "Nepali"
      proficiency: "100%"

SKILLS:
  enabled: true
  display_progress_bars: true
  display_percentage_values: false
  label: "My Skills"
  items:
    - skill: "PHP/Laravel"
      proficiency: "100%"
    - skill: "NodeJS / ExpressJs"
      proficiency: "100%"
    - skill: "NestJS"
      proficiency: "100%"
    - skill: "Python"
      proficiency: "100%"
    - skill: "MongoDB"
      proficiency: "100%"
    - skill: "MySQL"
      proficiency: "100%"
